### PR TITLE
added simple DPoP AT Hash

### PR DESCRIPTION
**Pull request by jricher**

### CODE REVIEW

**Comment by bc-pi** [comment]
Thanks Justin. Good food for thought, as you said. And this is pretty much how I would have written it, if I had written it. A few tweaks to the into and security considerations language is probably in order too, if this gets incorporated (mostly a note to myself).

**Review by KaycoinsInc — APPROVED** [review]

**Comment by danielfett** [comment]
I was on vacation and missed the interim meeting, so I'm not sure if this has been discussed before: Can we come up with an attack that is prevented by `ath`? 

It seems that `ath` prevents two kinds of attack approaches:

1. An attacker has a time window with access to the signature oracle and can precompute proofs, but **does not already know** the access token (including the case where the access token is rotated later).
2. An attacker has learned a DPoP proof and an access token from two different flows, both however bound to the same DPoP key, and wants to use them together.


Are there other scenarios?

**Comment by jricher** [comment]
@danielfett Scenario (2) is the one that I was mostly thinking of -- re-use of a proof from one token with a different token. This could be a rotated token (using the proof from the old value with the new value) or a separate token (maybe for a different user?).

**Comment by danielfett** [comment]
Let's try to sketch an attack. Maybe a compromised reverse proxy seeing two requests:

(a)
AT for User A,
POST /user/update
DPoP Proof:
```
{
  "jti":"-BwC3ESc6acc2lTc",
  "htm":"POST",
  "htu":"https://server.example.com/user/update",
  "iat":1562262616
}
```

(b) 
AT for User B
GET /user/details
DPoP Proof:
```
{
  "jti":"C3ESc6acc2lTcXYZ",
  "htm":"GET",
  "htu":"https://server.example.com/user/details",
  "iat":1562262616
}
```

Now the attacker can assemble:
(c)
AT for User B
POST /user/update
DPoP Proof:
```
{
  "jti":"-BwC3ESc6acc2lTc",
  "htm":"POST",
  "htu":"https://server.example.com/user/update",
  "iat":1562262616
}
```

This would be prevented by `ath`.

**Comment by jricher** [comment]
This sketch gets at one of the potentially bad corners of this kind of substitution attack -- submit a higher-powered token along with a proof created for a request with a lower-powered token. The attacker can create a failing signed request for the low-powered token to get the proof, then substitute the high-powered token value in the request with their proof.

(a)
Valid request for different resource with high-powered token AT-1

(b)
Invalid request with low-powered token AT-2 for different resource

(c)
Attacker combines token value from (a) with proof from (b) to successfully request resource in (b) using token from (a) even though client never created a valid signed request for the resource.

**Comment by danielfett** [comment]
Do we need to discuss this in the security considerations?

**Comment by bc-pi** [comment]
The thing I had in mind was more of a scenario (2) thing.  
An attacker with access to the signature oracle exfiltrate the access and refresh token along with pre-computed proofs that would allow for the RT to be exchanged for new access tokens and pre-computed proofs that would work with those access tokens for prolonged resource access. An `ath` would limit the window of such an 'offline' attack because future AT's obtained with the RT would be unusable.

**Comment by danielfett** [comment]
Both scenarios make sense. +1 for including the `ath` in DPoP.

**Review by danielfett — APPROVED** [review]

**Review by tlodderstedt — APPROVED** [review]
+1

**Comment by bc-pi** [comment]
example(s) need updating as well

**Comment by b---c** [comment]
also need JWT Claims Registration for ath

**Pull request merged**
