### PR TITLE
better(?) language around the 401 challenge (ostensibly for #119)

### PR DESCRIPTION
**Pull request by b---c**

### CODE REVIEW

**Review by selfissued — CHANGES_REQUESTED** [review]
"Can" or "MAY" is correct.  The server doesn't have to respond with a challenge.  It always has the option to simply fail the request.

This PR should be closed or modified since it appears to make a requirement for the server to respond with a challenge, when it can choose not to do so.

**Comment by jogu** [comment]
> "Can" or "MAY" is correct. The server doesn't have to respond with a challenge. It always has the option to simply fail the request.

@selfissued https://datatracker.ietf.org/doc/html/rfc6750#section-3 contains language like this:

>   If the protected resource request does not include authentication
>   credentials or does not contain an access token that enables access
>   to the protected resource, the resource server MUST include the HTTP
>   "WWW-Authenticate" response header field

To check my understanding, are you saying that 6750 is too strict here, or that 6750 is good but DPoP is deliberately less prescriptive?

I think it really helps the people implementing clients if the behaviour is prescriptively defined, at least for the cases where you would expect the client to automatically recover (e.g. if the presented access token has expired and the client has a refresh token available).

**Comment by bc-pi** [comment]
Agree that the server always has the option to simply fail the request. I wasn't intending to change that - only clean up the language a bit. I was surprised at first to see @selfissued push back on removing this one work. But I can kinda see the point now. And note that the 6750 MUST is about the www-auth header where the dpop text is about header and 401, so there's some subtleties in the comparison.

**Comment by bc-pi** [comment]
It looks like the text in question was also borrowed in part from [section 2 of The 'Basic' HTTP Authentication Scheme](https://datatracker.ietf.org/doc/html/rfc7617#section-2)  where it says, 
 > Upon receipt of a request for a URI within the protection space that
   lacks credentials, the server can reply with a challenge using the
   401 (Unauthorized) status code ([[RFC7235], Section 3.1](https://datatracker.ietf.org/doc/html/rfc7235#section-3.1)) and the
   WWW-Authenticate header field ([[RFC7235], Section 4.1](https://datatracker.ietf.org/doc/html/rfc7235#section-4.1)).

**Comment by b---c** [comment]
Modified the PR

**Comment by bc-pi** [comment]
Modified the PR with [b352b25](https://github.com/danielfett/draft-dpop/pull/122/commits/b352b25cb8c051067c147eb8b2f681be039f5b7a) so that paragraph would be: 

>Upon receipt of a request to a protected resource within the protection space requiring DPoP authentication, if the request does not include valid credentials or does not contain an access token sufficient for access, the server can respond with a challenge to the client to provide DPoP authentication information. Such a challenge is made using the 401 (Unauthorized) response status code ([[RFC7235](file:///Users/briancampbell/dev/dpop-oauth/draft-dpop/draft.html#RFC7235)], Section 3.1) and the WWW-Authenticate header field ([[RFC7235](file:///Users/briancampbell/dev/dpop-oauth/draft-dpop/draft.html#RFC7235)], Section 4.1). The server MAY include the WWW-Authenticate header in response to other conditions as well.

**Review by selfissued — APPROVED** [review]
Make it so

**Comment by jogu** [comment]
Thanks all.

This part possibly reads a little oddly:

> the server can respond with a challenge to the client to provide DPoP authentication information

as I think this paragraph is dealing with all cases, so the challenge might be for a different reason than providing DPoP authentication (e.g. "get an access token with scope <x>" or "get an access token that hasn't expired" etc).

**Comment by b---c** [comment]
DPoP authentication information encompasses the proof and access token. Those aren't different reasons. They are more specific instances of the general.

**Comment by jogu** [comment]
Thanks Brian. That is something I'd not appreciated.

**Pull request merged**
