### PR TITLE
Use a numbered list in 'Checking DPoP Proofs'

### PR DESCRIPTION
**Pull request by jogu**
This makes it easier to follow / easier to reference a particular check.

### CODE REVIEW

**Comment by jogu** [comment]
I checked the output html and it looks good.

I did think about numbering the two sub-bullets in point 12 but couldn't persuade mmark to use a different numbering format for the sub-list.

**Review by danielfett — APPROVED** [review]

**Comment by bc-pi** [comment]
Note that we moved away from numbered lists in -10 (noted here in doc history https://www.ietf.org/archive/id/draft-ietf-oauth-dpop-13.html#appendix-B-9.6 and done in https://github.com/danielfett/draft-dpop/commit/d36f361fbcb88bc32b3cb4e3c8807c62dcffd491) because there were some questions from folks that thought the numbering was a requirement on processing order.

**Comment by jogu** [comment]
Urgh. I’d forgotten about or never seen that, and should’ve checked - apologies.

Given the length of the list numbering them is really quite useful - would explicitly saying that the order is not significant be an acceptable alternative solution for the original concern?

**Comment by bc-pi** [comment]
Yeah, that'd be okay I think.

**Comment by jogu** [comment]
Thanks Brian. I've had a go at making that change; let me know how it looks.

**Comment by b---c** [comment]
Okay, good enough for me. Thanks.

**Pull request merged**
